pipelines:
  - name: Another_Pipeline
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo "Success"
