pipelines:
  - name: Chronological_STEP_LEVEL_PIPELINE
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
      - name: step2
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo "Success"
      - name: step3
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: step2
        execution:
          onExecute:
            - echo "Success"
      - name: step4
        type: Bash
        configuration:
          inputSteps:
            - name: step2
        execution:
          onExecute:
            - echo "Success"
