pipelines:
  - name: S_Matrix_MN_008
    steps:
      - name: S_Matrix_MN_008
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - foo: foo
            - foo: bar
            - foo: baz
        execution:
          onExecute:
            - echo $foo
