pipelines:
  - name: allow_failure_pipeline
    steps:
      - name: step1
        type: Bash
        configuration:
          allowFailure: true
        execution:
          onExecute:
            - echo 'step1'
            - exit 1
      - name: step2
        type: Bash
        configuration:
          allowFailure: true
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'failure'
