pipelines:
  - name: PIPE_9455_Workflow_03
    steps:
      - name: step1
        type: Bash
        configuration:
          allowFailure: false
        execution:
          onExecute:
            - echo 'step1'
            - exit 1
    - name: step2
      type: Bash
      configuration:
        allowFailure: true
        inputSteps:
          - name: step1
      execution:
        onExecute:
          - echo 'failure'
