pipelines:
  - name: timeout
    steps:
    - name: checkTimeout
      type: Bash
      execution:
        onExecute:
          - echo "Working fine"
          - sleep 10m
          - echo "Working fine"
    - name: end_timeout
      type: Bash
      configuration:
        inputSteps:
          - name: checkTimeout
      execution:
        onExecute:
          - echo "Working fine"
